
/////////////////////////////////////////////////////////////////////////////
// Name:        filenames-terms-abreviations.h
// Purpose:     Terms and concepts specific to Camelot
// Author:      Xoanon Graphics team
// Licence:     MIT
/////////////////////////////////////////////////////////////////////////////

/**

@page filenames-terms-abreviations Rendering Overview

@tableofcontents



 * Some history:



 * Specialized terms:

   @li @b MILLIPOINT: unit of the high precision logical coordinate
          space, i.e., our world. Roughly 1000th of a point (a pixel
          is ~3/4 the size of a point). Origin is (0,0) with negative
          numbers given their conventional Cartesean meaning. Roughly
          (but not precisely) the range of a signed 32 bit
          integer. Definition in camtypes.h

   @li @b spread
   @li @b render region
   @li @b chapter
   @li @b fixed16
   @li @b gdraw
   @li @b wxWidgets
   @li @b Camelot
   @li @b Xara
   @li @b Logical Coordinate
   @li @b view
   @li @b handle
   @li @b pasteboard



* Filenames
  - GDrawIntf GDraw Interface -- Interface to the GDraw binary-only
    library. Provides a C++ wrapper around the assembly languange
    routines.

    Classes: CriticalSection and GDrawAsm

  - XaDraw Xara GDraw -- Abstraction layer for GDraw V3.

  XaDrwOld

  @li @b aboutdlg: about dialog
  @li @b ai5_eps
  @li @b ai8_eps
  @li @b ai_bmp
  @li @b ai_eps
  @li @b ai_epsrr
  @li @b ai_grad
  @li @b ai_layer
  @li @b aligndlg
  @li @b animparams
  @li @b app
  @li @b appprefs
  @li @b appstate
  @li @b aprps
  @li @b archive
  @li @b arrows
  @li @b attr
  @li @b attraggl
  @li @b attrappl
  @li @b attrbev
  @li @b attrmap
  @li @b attrmgr
  @li @b attrval
  @li @b aw_eps
  @li @b backgrnd
  @li @b barcreationdlg
  @li @b barmsg
  @li @b bars
  @li @b basedoc
  @li @b becomea
  @li @b beveler
  @li @b bevfill
  @li @b bevtrap
  @li @b bfxatom
  @li @b bfxbase
  @li @b bfxdlg
  @li @b bfxdlg2
  @li @b bfxitem
  @li @b bfxmngr
  @li @b bfxop
  @li @b bfxopun
  @li @b bfxtest
  @li @b biasdlg
  @li @b biasgain
  @li @b biasgdgt
  @li @b binds
  @li @b bitfilt
  @li @b bitfopts
  @li @b bitmap
  @li @b bitmapcache
  @li @b bitmapcachekey
  @li @b bitmapfx
  @li @b bitmpinf
  @li @b bldbrdef
  @li @b blendatt
  @li @b blndhelp
  @li @b blobby
  @li @b blobs
  @li @b blppbrsh
  @li @b bmanip
  @li @b bmapprev
  @li @b bmpalctrl
  @li @b bmpalint
  @li @b bmpcomp
  @li @b bmpexdoc
  @li @b bmpexprw
  @li @b bmplist
  @li @b bmpprefs
  @li @b bmpsdlg
  @li @b bmpseq
  @li @b bmpsrc
  @li @b brndsel
  @li @b brpress
  @li @b brshattr
  @li @b brshbeca
  @li @b brshcomp
  @li @b brshdata
  @li @b brshgdgt
  @li @b brshname
  @li @b brushdlg
  @li @b brushmsg
  @li @b brushop
  @li @b brushref
  @li @b bshadow
  @li @b bshadow2
  @li @b cache
  @li @b cachfifo
  @li @b cachrand
  @li @b cachweak
  @li @b camconfig
  @li @b cameleps
  @li @b camfiltr
  @li @b camtypes
  @li @b capturemanager
  @li @b ccafile
  @li @b ccbhfile
  @li @b ccbuffil
  @li @b ccc
  @li @b ccfile
  @li @b ccmaths
  @li @b ccpanose
  @li @b cdrcol
  @li @b cdrfill
  @li @b cdrfiltr
  @li @b cdroutl
  @li @b cdrtext
  @li @b chapter
  @li @b clamp
  @li @b clicarea
  @li @b clipattr
  @li @b clipint
  @li @b cliptype
  @li @b cmdctrl
  @li @b cmxdcobj
  @li @b cmxexdc
  @li @b cmxfiltr
  @li @b cmxibits
  @li @b cmxicmds
  @li @b cmxidata
  @li @b cmxifltr
  @li @b cmxirefs
  @li @b cmxistut
  @li @b cmxrendr
  @li @b cmxtree
  @li @b cnamecol
  @li @b colcarry
  @li @b colclist
  @li @b colcomp
  @li @b colcontx
  @li @b coldlog
  @li @b colgal
  @li @b collist
  @li @b colmenu
  @li @b colmodel
  @li @b colmsg
  @li @b colormgr
  @li @b colourix
  @li @b colplate
  @li @b comattrmsg
  @li @b combshps
  @li @b contmenu
  @li @b control
  @li @b coord
  @li @b coplfilr
  @li @b coreleps
  @li @b cpyact
  @li @b crthumb
  @li @b csrstack
  @li @b cstroke
  @li @b cutop
  @li @b cxfarrow
  @li @b cxfcols
  @li @b cxfdash
  @li @b cxfdefs
  @li @b cxfellp
  @li @b cxfile
  @li @b cxflists
  @li @b cxfmap
  @li @b cxfnbmp
  @li @b cxfpoly
  @li @b cxfrec
  @li @b cxfrech
  @li @b cxfrect
  @li @b cxfrgshp
  @li @b cxftags
  @li @b cxftext
  @li @b cxftfile
  @li @b cxftrans
  @li @b cxftree
  @li @b cxfunits
  @li @b davedlg
  @li @b daveimp
  @li @b dbgthumb
  @li @b dbugtree
  @li @b debugdlg
  @li @b defalloc
  @li @b dialogop
  @li @b doccolor
  @li @b doccomp
  @li @b doccoord
  @li @b docmsgs
  @li @b docrect
  @li @b docrectdr
  @li @b document
  @li @b docview
  @li @b docvmsg
  @li @b draginfo
  @li @b dragmsg
  @li @b drawfltr
  @li @b dumbnode
  @li @b editsel
  @li @b effects_stack
  @li @b epscdef
  @li @b epsclist
  @li @b epsfiltr
  @li @b epssitem
  @li @b epsstack
  @li @b exagal
  @li @b exjpeg
  @li @b expbmp
  @li @b expcol
  @li @b exphint
  @li @b exprview
  @li @b extender
  @li @b extendsetsdlg
  @li @b ezmodule
  @li @b f16spec
  @li @b fileform
  @li @b filelist
  @li @b fillattr
  @li @b fillattr2
  @li @b fillcomp
  @li @b fillndge
  @li @b fillramp
  @li @b fillval
  @li @b filter_types
  @li @b filters
  @li @b filtimag
  @li @b filtimop
  @li @b filtirr
  @li @b filtrmgr
  @li @b fimagdlg
  @li @b finfodlg
  @li @b fitcurve
  @li @b fix24
  @li @b fixed
  @li @b fixed16
  @li @b fixed24
  @li @b flags
  @li @b flatfact
  @li @b fntcache
  @li @b fontcomp
  @li @b fontlist
  @li @b fontman
  @li @b fracfill
  @li @b fraclist
  @li @b frameops
  @li @b freeeps
  @li @b ftfilter
  @li @b fthrattr
  @li @b fthrconv
  @li @b fttyplis
  @li @b gadget
  @li @b gallery
  @li @b gblend
  @li @b gcache
  @li @b gclip
  @li @b gclips
  @li @b genlist
  @li @b genstack
  @li @b genv
  @li @b gla
  @li @b glatable
  @li @b gmould
  @li @b gradtbl
  @li @b gradtype
  @li @b grid
  @li @b group
  @li @b groupops
  @li @b grptrans
  @li @b guides
  @li @b gwinding
  @li @b helpids
  @li @b helpuser
  @li @b hittest
  @li @b hlinkdlg
  @li @b hotkeys
  @li @b htmlexp
  @li @b htmlfltr
  @li @b htmllist
  @li @b imagemap
  @li @b imjpeg
  @li @b impbmp
  @li @b impcol
  @li @b impexpop
  @li @b impstr
  @li @b inetop
  @li @b infobar
  @li @b infocomp
  @li @b ink
  @li @b input
  @li @b insertnd
  @li @b invalid
  @li @b iprofile
  @li @b isetattr
  @li @b iterator
  @li @b jerror
  @li @b jpgdest
  @li @b jpgermgr
  @li @b jpglib_namespace
  @li @b jpgprgrs
  @li @b jpgsrc
  @li @b kernel
  @li @b kerneldc
  @li @b keymsg
  @li @b la_base
  @li @b lattrops
  @li @b layer
  @li @b layerdlg
  @li @b layergal
  @li @b layermgr
  @li @b layermsg
  @li @b layerprp
  @li @b lineattr
  @li @b linecomp
  @li @b linedef
  @li @b linwthop
  @li @b list
  @li @b listitem
  @li @b loadbrsh
  @li @b logname
  @li @b macros
  @li @b main
  @li @b main1
  @li @b main2
  @li @b main3
  @li @b makebmp
  @li @b maskedrr
  @li @b matrix
  @li @b menuitem
  @li @b menuops
  @li @b mkshapes
  @li @b mkstroke
  @li @b modlist
  @li @b module
  @li @b moldedit
  @li @b moldenv
  @li @b moldpers
  @li @b moldshap
  @li @b mrhbits
  @li @b msg
  @li @b namedlg
  @li @b native
  @li @b nativeop
  @li @b nativeps
  @li @b nbevcont
  @li @b ncntrcnt
  @li @b ndbldpth
  @li @b ndbrshmk
  @li @b ndbrshpt
  @li @b ndcchbmp
  @li @b ndclpcnt
  @li @b ndmldgrp
  @li @b ndmldink
  @li @b ndmldpth
  @li @b ndoptmz
  @li @b ndtxtpth
  @li @b newcol
  @li @b ngcore
  @li @b ngdialog
  @li @b ngdrag
  @li @b ngitem
  @li @b ngiter
  @li @b ngprop
  @li @b ngscan
  @li @b ngsentry
  @li @b ngsetop
  @li @b node
  @li @b nodeabmp
  @li @b nodeattr
  @li @b nodebev
  @li @b nodebldr
  @li @b nodeblnd
  @li @b nodebmp
  @li @b nodebrsh
  @li @b nodecach
  @li @b nodeclip
  @li @b nodecntr
  @li @b nodecomp
  @li @b nodecont
  @li @b nodedoc
  @li @b nodeelip
  @li @b nodeliveeffect
  @li @b nodemldr
  @li @b nodemold
  @li @b nodepath
  @li @b nodepostpro
  @li @b noderect
  @li @b noderend
  @li @b nodershp
  @li @b nodeset
  @li @b nodeshad
  @li @b nodeshap
  @li @b nodetext
  @li @b nodetxtl
  @li @b nodetxts
  @li @b noise1
  @li @b noisebas
  @li @b noisef
  @li @b npaper
  @li @b objcache
  @li @b objchge
  @li @b objreg
  @li @b offattr
  @li @b opbarcreation
  @li @b opbreak
  @li @b opdesc
  @li @b opdragbx
  @li @b opdupbar
  @li @b opfeathr
  @li @b opgrad
  @li @b ophist
  @li @b opimgset
  @li @b opnode
  @li @b opnudge
  @li @b oppull
  @li @b ops
  @li @b opsmooth
  @li @b opsmpshp
  @li @b optsedit
  @li @b optsgrid
  @li @b optsinet
  @li @b optsmisc
  @li @b optsmsgs
  @li @b optspage
  @li @b optsplug
  @li @b optspntr
  @li @b optsprin
  @li @b optsscal
  @li @b optstune
  @li @b optsundo
  @li @b optsunit
  @li @b optsview
  @li @b opwhat
  @li @b opwiz
  @li @b ordlist
  @li @b overitem
  @li @b overlist
  @li @b page
  @li @b pagesize
  @li @b paldefs
  @li @b palmenu
  @li @b paper
  @li @b pathedit
  @li @b pathndge
  @li @b pathops
  @li @b pathpcs
  @li @b pathproc
  @li @b paths
  @li @b pathshap
  @li @b pathstrk
  @li @b pathtrap
  @li @b pathtype
  @li @b pathutil
  @li @b pbecomea
  @li @b penedit
  @li @b plugin
  @li @b plugmngr
  @li @b plugop
  @li @b plugopun
  @li @b pmaskrgn
  @li @b pngfuncs
  @li @b pngprgrs
  @li @b ppairbsh
  @li @b ppbevel
  @li @b ppbrush
  @li @b ppstroke
  @li @b ppvecstr
  @li @b prefs
  @li @b pressure
  @li @b prevwdlg
  @li @b princomp
  @li @b printctl
  @li @b printing
  @li @b printmsg
  @li @b prnmkcom
  @li @b prnmks
  @li @b prnprefs
  @li @b prntview
  @li @b property
  @li @b prpsgds
  @li @b prpslyrs
  @li @b prvwflt
  @li @b prvwmenu
  @li @b psrndrgn
  @li @b pump
  @li @b qualattr
  @li @b quality
  @li @b qualops
  @li @b radio
  @li @b range
  @li @b rechattr
  @li @b rechblnd
  @li @b rechbmp
  @li @b rechbmpp
  @li @b rechcol
  @li @b rechcomp
  @li @b rechdoc
  @li @b rechellp
  @li @b rechgrp
  @li @b rechinfo
  @li @b rechmld
  @li @b rechpath
  @li @b rechpoly
  @li @b rechprnt
  @li @b rechrect
  @li @b rechrshp
  @li @b rechshad
  @li @b rechsmth
  @li @b rechtext
  @li @b rechunit
  @li @b rechview
  @li @b rect
  @li @b region
  @li @b release
  @li @b renddlg
  @li @b rgnlist
  @li @b rifffile
  @li @b rndctrl
  @li @b rnddlgs
  @li @b rndrgn
  @li @b rndstack
  @li @b rrcaps
  @li @b rsmooth
  @li @b rulers
  @li @b samplist
  @li @b saveeps
  @li @b scanrr
  @li @b scrnview
  @li @b scunit
  @li @b selall
  @li @b selmedia
  @li @b selmsg
  @li @b selop
  @li @b selstate
  @li @b sentryop
  @li @b sgallery
  @li @b sgbase
  @li @b sgbitmap
  @li @b sgbrush
  @li @b sgcolour
  @li @b sgdrag
  @li @b sgframe
  @li @b sginit
  @li @b sglayer
  @li @b sglbase
  @li @b sglcart
  @li @b sglfills
  @li @b sglib
  @li @b sgline
  @li @b sgline2
  @li @b sgmenu
  @li @b sgname
  @li @b sgscan
  @li @b sgscanf
  @li @b sgstroke
  @li @b sgtree
  @li @b shapeops
  @li @b slice
  @li @b slicehelper
  @li @b slowjob
  @li @b snap
  @li @b snapops
  @li @b sprdmsg
  @li @b spread
  @li @b stack
  @li @b statline
  @li @b stdbars
  @li @b stl
  @li @b stockcol
  @li @b strkattr
  @li @b strkcomp
  @li @b strlist
  @li @b styles
  @li @b swfbitmp
  @li @b swfbuttn
  @li @b swfexpdc
  @li @b swffiltr
  @li @b swffont
  @li @b swfplace
  @li @b swfrndr
  @li @b swfshape
  @li @b swfsprit
  @li @b swftext
  @li @b taglists
  @li @b test
  @li @b textacts
  @li @b textfltr
  @li @b thumbmsg
  @li @b timespan
  @li @b tipsdlg
  @li @b tmpltarg
  @li @b tmpltatr
  @li @b tmpltdlg
  @li @b tool
  @li @b tooldlg
  @li @b toollist
  @li @b toolmsg
  @li @b tracectl
  @li @b tracedlg
  @li @b tracergn
  @li @b tranform
  @li @b trans2d
  @li @b transop
  @li @b txtattr
  @li @b uielem
  @li @b undoop
  @li @b unitcomp
  @li @b unitres
  @li @b units
  @li @b unittype
  @li @b urldlg
  @li @b urlimp
  @li @b userattr
  @li @b usercord
  @li @b userrect
  @li @b userrectdr
  @li @b valfunc
  @li @b vector
  @li @b vector3d
  @li @b vectrndr
  @li @b view
  @li @b viewcomp
  @li @b viewmenu
  @li @b visiattr
  @li @b webaddr
  @li @b webattr
  @li @b webfiltr
  @li @b webflags
  @li @b webop
  @li @b webparam
  @li @b webprefs
  @li @b wrkcoord
  @li @b wrkrect
  @li @b xagdraw
  @li @b xarprefs
  @li @b xlong
  @li @b xmatrix
  @li @b xpeoptokens
  @li @b xpfcaps
  @li @b xpfilter
  @li @b xpfrgn
  @li @b xsepsops
  @li @b zconf
  @li @b zdeflate
  @li @b zdftrees
  @li @b ziftrees
  @li @b zinflate
  @li @b zlib
  @li @b zordops
  @li @b zstream
  @li @b zutil

* @li @b Non-c++
  @li @b all.lst
  @li @b blends.ps
  @li @b docrect.dec
  @li @b docrect.def
  @li @b docrect.map
  @li @b exports.txt
  @li @b genprocs.ps
  @li @b gradfill.ps
  @li @b groups.ps
  @li @b kernel.mak
  @li @b pathproc.ps
  @li @b ps.mak
  @li @b rect.ctt
  @li @b rect.map
  @li @b setup.ps
  @li @b spotfunc.ps
  @li @b txtprocs.ps
  @li @b userrect.dec
  @li @b userrect.def
  @li @b userrect.map
  @li @b wrkrect.map


* obsolete
  mssccprj.scc

**/
